name: Build and Terraform Plan 

on: 
  push: 
    branches:
      - main

jobs:
  build-java:
    name: Build Konvo Spring Project 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java 
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'
      
      - name: Build with maven
        working-directory: ./konvo
        run: mvn clean install
  
  terraform-plan:
    name: Terraform plan 
    runs-on: ubuntu-latest
    needs: build-java 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.6.6

      - name: Initialize terraform 
        working-directory: ./konvo-infra
        run: terraform init

      - name: Terraform Format check 
        working-directory: ./konvo-infra
        run: terraform fmt -check 

      - name: Terraform Validate 
        working-directory: ./konvo-infra
        run: terraform validate 

      - name: Terraform Plan
        working-directory: ./konvo-infra
        run: terraform plan 